connections:
  snowflake:
    snowflake:
      account: fka56740
      warehouse: COMPUTE_WH
      role: SYSADMIN
      auth_type: snowflake
      username: SWALKER2
      password: SnowCoaFlakeLesce2024
      databases: [SWALKER_DB_DEV]
  snowflake_target:
    snowflake:
      account: fka56740
      warehouse: COMPUTE_WH
      role: SYSADMIN
      auth_type: snowflake
      username: SWALKER2
      password: SnowCoaFlakeLesce2024
      databases: [SWALKER_DB_DEV]
