fileVersion: 1
id: "18"
mappingDefinitions:
  BRONZE:
    database: NY_TAXI
    schema: BRONZE
  GOLD:
    database: PRODUCTION
    schema: PRESENTATION
  ICEBERG:
    database: PRODUCTION
    schema: DV_STAGING
  SILVER:
    database: PRODUCTION
    schema: MODELLED
  SYNQ_AUDIT:
    database: NY_TAXI
    schema: SYNQ
name: Production
type: Environment
