fileVersion: 1
id: "219"
mappingDefinitions:
  BRONZE_MEWBOURNE:
    database: JJ_DEV
    schema: JJ_DEV_SCHEMA
  GOLD:
    database: ""
    schema: ""
  SILVER:
    database: ""
    schema: ""
name: Production - Mewbourne Oil
type: Environment
