fileVersion: 1
id: "182"
mappingDefinitions:
  BRONZE_MEWBOURNE:
    database: ""
    schema: ""
  GOLD:
    database: ""
    schema: ""
  SILVER:
    database: ""
    schema: ""
name: Production
type: Environment
