fileVersion: 1
id: "18"
mappingDefinitions:
  BRONZE:
    database: SWALKER_DB_DEV
    schema: TAXI_SRC
  GOLD:
    database: SWALKER_DB
    schema: TAXI_GOLD
  ICEBERG:
    database: PRODUCTION
    schema: DV_STAGING
  SILVER:
    database: SWALKER_DB
    schema: TAXI_SILVER
  SYNQ_AUDIT:
    database: NY_TAXI
    schema: SYNQ
name: Production
type: Environment
