fileVersion: 1
id: "219"
mappingDefinitions:
  BRONZE_MEWBOURNE:
    database: JJ_DEV
    schema: JJ_DEV_SCHEMA
  DWH:
    database: placeholder
    schema: placeholder
  GOLD:
    database: JJ_PROD
    schema: JJ_PROD_SCHEMA
  SILVER:
    database: JJ_PROD
    schema: JJ_PROD_SCHEMA
  SRC_FIVETRAN_RETAIL:
    database: placeholder
    schema: placeholder
  SRC_SAMPLE:
    database: placeholder
    schema: placeholder
  SRC_WEATHER:
    database: placeholder
    schema: placeholder
  STAGE:
    database: placeholder
    schema: placeholder
name: Production - Mewbourne Oil
type: Environment
