@id("4a44850c-ab8c-49ef-8a12-89516a0e7189")
@nodeType("176")
SELECT
     "L_ORDERKEY" AS "L_ORDERKEY",
     "L_PARTKEY" AS "L_PARTKEY",
     "L_SUPPKEY" AS "L_SUPPKEY",
     "L_LINENUMBER" AS "L_LINENUMBER",
     "L_QUANTITY" AS "L_QUANTITY",
     "L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE",
     "L_DISCOUNT" AS "L_DISCOUNT",
     "L_TAX" AS "L_TAX",
     "L_RETURNFLAG" AS "L_RETURNFLAG",
     "L_LINESTATUS" AS "L_LINESTATUS",
     "L_SHIPDATE" AS "L_SHIPDATE",
     "L_COMMITDATE" AS "L_COMMITDATE",
     "L_RECEIPTDATE" AS "L_RECEIPTDATE",
     "L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT",
     "L_SHIPMODE" AS "L_SHIPMODE",
     "L_COMMENT" AS "L_COMMENT"
FROM {{ ref('SRC_SAMPLE', 'LINEITEM') }} "LINEITEM"