@id("84eb2fcd-c7a1-48d8-9098-34bdc0641c77")
@nodeType("176")
SELECT
     "C_CUSTKEY" AS "C_CUSTKEY",
     "C_NAME" AS "C_NAME",
     "C_ADDRESS" AS "C_ADDRESS",
     "C_NATIONKEY" AS "C_NATIONKEY",
     "C_PHONE" AS "C_PHONE",
     "C_ACCTBAL" AS "C_ACCTBAL",
     "C_MKTSEGMENT" AS "C_MKTSEGMENT",
     "C_COMMENT" AS "C_COMMENT"
FROM {{ ref('SRC_SAMPLE', 'CUSTOMER') }} "CUSTOMER"