@id("afe1ac64-6960-4dbe-834c-314d33247937")
@nodeType("176")
SELECT
     "PS_PARTKEY" AS "PS_PARTKEY",
     "PS_SUPPKEY" AS "PS_SUPPKEY",
     "PS_AVAILQTY" AS "PS_AVAILQTY",
     "PS_SUPPLYCOST" AS "PS_SUPPLYCOST",
     "PS_COMMENT" AS "PS_COMMENT"
FROM {{ ref('SRC_SAMPLE', 'PARTSUPP') }} "PARTSUPP"