@id("e69a750f-ade5-4da2-a0f1-a28eaf0737af")
@nodeType("6")

WITH HIRE_DATE AS (
     SELECT VENDOR_ID, MAX(HIRE_DATE) "MAX_HIRE_DATE"
     FROM {{ ref('BRONZE', 'DRIVERS') }} "DRIVERS"
     GROUP BY VENDOR_ID

)

SELECT
     "DRIVER_ID" AS "DRIVER_ID",
     "DRIVERS"."VENDOR_ID"::STRING AS "VENDOR_ID",
     "FIRST_NAME" AS "FIRST_NAME",
     "LAST_NAME" AS "LAST_NAME",
     "LICENSE_NUMBER" AS "LICENSE_NUMBER",
     "LICENSE_EXPIRY" AS "LICENSE_EXPIRY",
     "PHONE" AS "PHONE",
     "EMAIL" AS "EMAIL",
     "HIRE_DATE" AS "HIRE_DATE",
     "RATING" AS "RATING",
     "IS_ACTIVE" AS "IS_ACTIVE",
     "MAX_HIRE_DATE" AS "MAX_HIRE_DATE"
FROM {{ ref('BRONZE', 'DRIVERS') }} "DRIVERS"
LEFT JOIN "HIRE_DATE" "HIRE_DATE" on "DRIVERS"."VENDOR_ID" = "HIRE_DATE"."VENDOR_ID"