@id("f17f5d10-4555-4d70-8675-4c5a25b33d9b")
@nodeType("6")
SELECT
     "VENDOR_ID" AS "VENDOR_ID",
     "PAYMENT_TYPE_ID" AS "PAYMENT_TYPE_ID",
     "RATE_CODE_ID" AS "RATE_CODE_ID",
     "PICKUP_DATETIME" AS "PICKUP_DATETIME",
     "DROPOFF_DATETIME" AS "DROPOFF_DATETIME",
     "DO_LOCATION_ID" AS "DO_LOCATION_ID",
     "PU_LOCATION_ID" AS "PU_LOCATION_ID",
     "TRIP_DISTANCE" AS "TRIP_DISTANCE",
     "TRIP_DURATION_MINUTES" AS "TRIP_DURATION_MINUTES",
     "TRIP_AVG_SPEED" AS "TRIP_AVG_SPEED",
     "PICKUP_TIME_OF_DAY" AS "PICKUP_TIME_OF_DAY",
     "AIRPORT_FEE" AS "AIRPORT_FEE",
     "CBD_CONGESTION_FEE" AS "CBD_CONGESTION_FEE",
     "CONGESTION_SURCHARGE" AS "CONGESTION_SURCHARGE",
     "EXTRA" AS "EXTRA",
     "FARE_AMOUNT" AS "FARE_AMOUNT",
     "IMPROVEMENT_SURCHARGE" AS "IMPROVEMENT_SURCHARGE",
     "MTA_TAX" AS "MTA_TAX",
     "PASSENGER_COUNT" AS "PASSENGER_COUNT",
     "STORE_AND_FWD_FLAG" AS "STORE_AND_FWD_FLAG",
     "TIP_AMOUNT" AS "TIP_AMOUNT",
     "TOLLS_AMOUNT" AS "TOLLS_AMOUNT",
     "TOTAL_AMOUNT" AS "TOTAL_AMOUNT",
     "TPEP_PICKUP_DATETIME" AS "TPEP_PICKUP_DATETIME",
     "TPEP_DROPOFF_DATETIME" AS "TPEP_DROPOFF_DATETIME"
FROM {{ ref('SILVER', 'STG_YELLOW_CAB_TRIPS') }} "STG_YELLOW_CAB_TRIPS"