@id("f181db0d-6bc6-4965-9a58-1bc421607b14")
@nodeType("6")
SELECT
  TRIP_ID,
  FILE_NAME,
  VENDOR_ID,
  PAYMENT_TYPE_ID,
  RATE_CODE_ID,
  PICKUP_DATETIME,
  DROPOFF_DATETIME,
  DO_LOCATION_ID,
  PU_LOCATION_ID,
  TRIP_DISTANCE,
  DATEDIFF(MINUTE, PICKUP_DATETIME, DROPOFF_DATETIME) AS TRIP_DURATION_MINUTES,
  DIV0(TRIP_DISTANCE, DATEDIFF(MINUTE, PICKUP_DATETIME, DROPOFF_DATETIME)) * 60 AS TRIP_AVG_SPEED,
  CASE WHEN DATEDIFF(HOUR, TO_DATE(PICKUP_DATETIME), PICKUP_DATETIME) < 12 THEN 'MORNING' ELSE 'AFTERNOON' END AS PICKUP_TIME_OF_DAY,
  AIRPORT_FEE,
  CBD_CONGESTION_FEE,
  CONGESTION_SURCHARGE,
  EXTRA,
  FARE_AMOUNT,
  IMPROVEMENT_SURCHARGE,
  MTA_TAX,
  PASSENGER_COUNT,
  STORE_AND_FWD_FLAG,
  TIP_AMOUNT,
  TOLLS_AMOUNT,
  TOTAL_AMOUNT,
  COALESCE(FARE_AMOUNT, 0) + COALESCE(EXTRA, 0) + COALESCE(MTA_TAX, 0)
    + COALESCE(TIP_AMOUNT, 0) + COALESCE(TOLLS_AMOUNT, 0) + COALESCE(IMPROVEMENT_SURCHARGE, 0)
    + COALESCE(CONGESTION_SURCHARGE, 0) + COALESCE(AIRPORT_FEE, 0)
    + COALESCE(CBD_CONGESTION_FEE, 0) AS TOTAL_COMPONENT_SUM,
  TPEP_PICKUP_DATETIME,
  TPEP_DROPOFF_DATETIME,
  LOAD_DATE,
  LAST_MODIFIED_TS
FROM {{ ref("BRONZE", "TRIPS") }}
WHERE LAST_MODIFIED_TS > (SELECT COALESCE(MAX(LAST_MODIFIED_TS), '1899-01-01') FROM {{ ref_no_link("SILVER", "ODS_YELLOW_CAB_TRIPS") }})
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIP_ID ORDER BY LAST_MODIFIED_TS DESC) = 1
