@id("1d686eaf-763d-47ae-abc1-91963605ae83")
@nodeType("6")

SELECT
    T.TRIP_ID,
    T.VENDOR_ID,
    V.VENDOR_NAME,
    T.PAYMENT_TYPE_ID,
    PT.PAYMENT_TYPE,
    T.RATE_CODE_ID,
    RC.RATE_CODE,
    T.PICKUP_DATETIME,
    T.DROPOFF_DATETIME,
    T.PU_LOCATION_ID,
    PU.BOROUGH AS PU_BOROUGH,
    T.DO_LOCATION_ID,
    DO_LOC.BOROUGH AS DO_BOROUGH,
    T.TRIP_DISTANCE,
    T.TRIP_DURATION_MINUTES,
    T.TRIP_AVG_SPEED,
    T.PICKUP_TIME_OF_DAY,
    T.AIRPORT_FEE,
    T.CBD_CONGESTION_FEE,
    T.CONGESTION_SURCHARGE,
    T.EXTRA,
    T.FARE_AMOUNT,
    T.IMPROVEMENT_SURCHARGE,
    T.MTA_TAX,
    T.PASSENGER_COUNT,
    T.STORE_AND_FWD_FLAG,
    T.TIP_AMOUNT,
    T.TOLLS_AMOUNT,
    T.TOTAL_AMOUNT,
    T.TOTAL_COMPONENT_SUM,
    T.LOAD_DATE
FROM {{ ref("SILVER", "ODS_YELLOW_CAB_TRIPS") }} T
LEFT JOIN {{ ref("GOLD", "DIM_VENDOR") }} V
    ON T.VENDOR_ID = V.VENDOR_ID AND V.SYSTEM_CURRENT_FLAG = 'Y'
LEFT JOIN {{ ref("GOLD", "DIM_PAYMENT_TYPE") }} PT
    ON T.PAYMENT_TYPE_ID = PT.PAYMENT_TYPE_ID AND PT.SYSTEM_CURRENT_FLAG = 'Y'
LEFT JOIN {{ ref("GOLD", "DIM_RATE_CODE") }} RC
    ON T.RATE_CODE_ID = RC.RATE_CODE_ID AND RC.SYSTEM_CURRENT_FLAG = 'Y'
LEFT JOIN {{ ref("GOLD", "DIM_LOCATION") }} PU
    ON T.PU_LOCATION_ID = PU.LOCATION_ID AND PU.SYSTEM_CURRENT_FLAG = 'Y'
LEFT JOIN {{ ref("GOLD", "DIM_LOCATION") }} DO_LOC
    ON T.DO_LOCATION_ID = DO_LOC.LOCATION_ID AND DO_LOC.SYSTEM_CURRENT_FLAG = 'Y'
WHERE T.SYSTEM_CURRENT_FLAG = 'Y'
  AND T.TOTAL_AMOUNT > 0
  -- Exclude non-credit-card trips on reconciliation days (test data cleanup)
  AND NOT (
      T.PAYMENT_TYPE_ID IN (2, 3, 4)
      AND DAYOFWEEKISO(CURRENT_DATE()) IN (2, 4)
  )
