@id("ac4a4790-1c72-49c2-bf7f-94dafdbfc151")
@nodeType("8")
SELECT
     "DRIVER_ID" AS "DRIVER_ID" @isBusinessKey,
     "VENDOR_ID" AS "VENDOR_ID",
     "FIRST_NAME" AS "FIRST_NAME",
     "LAST_NAME" AS "LAST_NAME",
     "LICENSE_NUMBER" AS "LICENSE_NUMBER",
     "LICENSE_EXPIRY" AS "LICENSE_EXPIRY",
     "PHONE" AS "PHONE",
     "EMAIL" AS "EMAIL",
     "HIRE_DATE" AS "HIRE_DATE",
     "RATING" AS "RATING",
     "IS_ACTIVE" AS "IS_ACTIVE",
     "MAX_HIRE_DATE" AS "MAX_HIRE_DATE"
FROM {{ ref('SILVER', 'SQL_DRIVERS') }} "SQL_DRIVERS"