@id("38025cea-1f19-4c82-8065-32b79270060f")
@nodeType("10")
SELECT
     "VENDOR_ID" AS "VENDOR_ID" @isBusinessKey,
     "VENDOR_NAME" AS "VENDOR_NAME",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE"
FROM {{ ref('BRONZE', 'VENDOR') }} "VENDOR"