@id("d49998c3-8086-45c9-bbe0-cb90d7b8b28f")
@nodeType("6")
@testsEnabled
SELECT
  PAYMENT_TYPE_ID               @isBusinessKey @tests("SELECT * FROM {{ this }} WHERE PAYMENT_TYPE_ID IS NULL", "SELECT PAYMENT_TYPE_ID, COUNT(*) FROM {{ this }} GROUP BY PAYMENT_TYPE_ID HAVING COUNT(*) > 1"),
  PAYMENT_TYPE                  @tests("SELECT * FROM {{ this }} WHERE PAYMENT_TYPE IS NULL"),
  UPDATED_AT
FROM {{ ref("BRONZE", "PAYMENT_TYPE") }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY PAYMENT_TYPE_ID ORDER BY UPDATED_AT DESC) = 1
