@id("567ec716-0a53-4e84-930d-bfa612f368af")
@nodeType("6")
SELECT
  VENDOR_ID,
  YEAR(PICKUP_DATETIME) AS YEAR,
  MONTH(PICKUP_DATETIME) AS MONTH,
  MAX(VENDOR_NAME) AS VENDOR_NAME,
  COUNT(1) AS TRIP_COUNT,
  SUM(FARE_AMOUNT) AS TOTAL_FARE_AMOUNT,
  SUM(TOTAL_AMOUNT) AS TOTAL_AMOUNT,
  SUM(CASE WHEN PAYMENT_TYPE = 'Cash' THEN TOTAL_AMOUNT END) AS TOTAL_AMOUNT_CASH,
  SUM(CASE WHEN PAYMENT_TYPE = 'Credit card' THEN TOTAL_AMOUNT END) AS TOTAL_AMOUNT_CC,
  SUM(CASE WHEN PAYMENT_TYPE = 'Void' THEN TOTAL_AMOUNT END) AS TOTAL_AMOUNT_VOID,
  SUM(TRIP_DISTANCE) AS TRIP_DISTANCE_TOTAL,
  AVG(TRIP_DISTANCE) AS TRIP_DISTANCE_AVG,
  SUM(TRIP_DURATION_MINUTES) AS TRIP_DURATION_MINUTES_TOTAL
FROM {{ ref("GOLD", "FCT_YELLOW_CAB_TRIPS") }}
GROUP BY 1, 2, 3
