@id("cd9ff3ed-0ebc-4865-86a3-186bb19aebc0")
@nodeType("6")
SELECT
  VENDOR_ID,
  PAYMENT_TYPE_ID,
  RATE_CODE_ID,
  PICKUP_DATETIME,
  DROPOFF_DATETIME,
  DO_LOCATION_ID,
  PU_LOCATION_ID,
  TRIP_DISTANCE,
  DATEDIFF(MINUTE, PICKUP_DATETIME, DROPOFF_DATETIME) AS TRIP_DURATION_MINUTES,
  DIV0(TRIP_DISTANCE, DATEDIFF(MINUTE, PICKUP_DATETIME, DROPOFF_DATETIME)) * 60 AS TRIP_AVG_SPEED,
  CASE WHEN DATEDIFF(HOUR, TO_DATE(PICKUP_DATETIME), PICKUP_DATETIME) < 12 THEN 'MORNING' ELSE 'AFTERNOON' END AS PICKUP_TIME_OF_DAY,
  AIRPORT_FEE,
  CBD_CONGESTION_FEE,
  CONGESTION_SURCHARGE,
  EXTRA,
  FARE_AMOUNT,
  IMPROVEMENT_SURCHARGE,
  MTA_TAX,
  PASSENGER_COUNT,
  STORE_AND_FWD_FLAG,
  TIP_AMOUNT,
  TOLLS_AMOUNT,
  TOTAL_AMOUNT,
  TPEP_PICKUP_DATETIME,
  TPEP_DROPOFF_DATETIME
FROM {{ ref("BRONZE", "YELLOW_CAB_TRIPS") }}
WHERE TO_DATE(PICKUP_DATETIME) BETWEEN CURRENT_DATE - 30 AND CURRENT_DATE
