@id("6384942e-b835-4067-aa2d-114d3ad0a58f")
@nodeType("6")
SELECT
  T.VENDOR_ID,
  V.VENDOR_NAME,
  T.PAYMENT_TYPE_ID,
  P.PAYMENT_TYPE,
  T.RATE_CODE_ID,
  R.RATE_CODE,
  T.PICKUP_DATETIME,
  T.DROPOFF_DATETIME,
  T.PU_LOCATION_ID,
  PU.BOROUGH AS PU_BOROUGH,
  T.DO_LOCATION_ID,
  DO.BOROUGH AS DO_BOROUGH,
  P.DIM_PAYMENT_TYPE_KEY,
  R.DIM_RATE_CODE_KEY,
  V.DIM_VENDOR_KEY,
  PU.DIM_PICKUP_LOCATION_KEY,
  DO.DIM_DROPOFF_LOCATION_KEY,
  T.TRIP_DISTANCE,
  T.TRIP_DURATION_MINUTES,
  T.TRIP_AVG_SPEED,
  T.PICKUP_TIME_OF_DAY,
  T.AIRPORT_FEE,
  T.CBD_CONGESTION_FEE,
  T.CONGESTION_SURCHARGE,
  T.EXTRA,
  T.FARE_AMOUNT,
  T.IMPROVEMENT_SURCHARGE,
  T.MTA_TAX,
  T.PASSENGER_COUNT,
  T.STORE_AND_FWD_FLAG,
  T.TIP_AMOUNT,
  T.TOLLS_AMOUNT,
  T.TOTAL_AMOUNT
FROM {{ ref("SILVER", "STG_YELLOW_CAB_TRIPS") }} T
LEFT JOIN {{ ref("GOLD", "DIM_VENDOR") }} V ON T.VENDOR_ID = V.VENDOR_ID
LEFT JOIN {{ ref("GOLD", "DIM_PAYMENT_TYPE") }} P ON T.PAYMENT_TYPE_ID = P.PAYMENT_TYPE_ID
LEFT JOIN {{ ref("GOLD", "DIM_RATE_CODE") }} R ON T.RATE_CODE_ID = R.RATE_CODE_ID
INNER JOIN {{ ref("SILVER", "PICKUP_LOCATION") }} PU ON T.PU_LOCATION_ID = PU.LOCATION_ID
INNER JOIN {{ ref("SILVER", "DROPOFF_LOCATION") }} DO ON T.DO_LOCATION_ID = DO.LOCATION_ID
